/**
 * Note: GENERATED BY AI (gemini)
 */

package cz.fit.hotel.model;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;

public class JpaMappingTest {

    private static EntityManagerFactory emf;
    private EntityManager em;

    @BeforeAll
    public static void init() {
        // Loads the hotel-test-pu from persistence.xml
        emf = Persistence.createEntityManagerFactory("hotel-test-pu");
    }

    @AfterAll
    public static void tearDown() {
        if (emf != null)
            emf.close();
    }

    @BeforeEach
    public void setup() {
        em = emf.createEntityManager();
    }

    @AfterEach
    public void cleanup() {
        if (em != null)
            em.close();
    }

    @Test
    public void testCustomerReservationRelationship() {
        em.getTransaction().begin();

        Customer customer = new Customer("John Doe", LocalDate.of(1990, 1, 1), "john@example.com", "+123456789");
        em.persist(customer);

        RoomType standardType = new RoomType("Standard");
        em.persist(standardType);

        Room room = new Room("101", 2, new BigDecimal("100.00"), standardType);
        em.persist(room);

        Employee employee = new Employee("Jane Staff", "jane123", "contact", EmployeeRole.RECEPTIONIST); // Pass null or
                                                                                                         // a valid
                                                                                                         // EmployeeRole
        employee.setPassword("securePassword123!");
        em.persist(employee);

        Reservation reservation = new Reservation();
        reservation.setCheckInDate(LocalDate.now());
        reservation.setCheckOutDate(LocalDate.now().plusDays(3));
        reservation.setNumberOfGuests(2);
        reservation.setRoom(room);
        reservation.setEmployee(employee);

        customer.addReservation(reservation);
        em.persist(reservation);

        em.getTransaction().commit();
        em.clear();

        Customer savedCustomer = em.find(Customer.class, customer.getId());
        assertThat(savedCustomer.getReservations()).hasSize(1);

        Reservation savedReservation = savedCustomer.getReservations().iterator().next();
        assertThat(savedReservation.getCustomer().getName()).isEqualTo("John Doe");
        assertThat(savedReservation.getCreatedAt()).isNotNull(); // Proves @PrePersist worked
    }

    @Test
    public void testRoomAndRoomServiceManyToMany() {
        em.getTransaction().begin();

        RoomType deluxeType = new RoomType("Deluxe");
        em.persist(deluxeType);

        Room room = new Room("202", 4, new BigDecimal("250.00"), deluxeType);

        RoomService wifiService = new RoomService("Free Wi-Fi", "High speed internet");
        RoomService breakfastService = new RoomService("Breakfast", "Buffet included");
        em.persist(wifiService);
        em.persist(breakfastService);

        room.addService(wifiService);
        room.addService(breakfastService);

        em.persist(room);
        em.getTransaction().commit();
        em.clear();

        Room savedRoom = em.find(Room.class, room.getId());
        assertThat(savedRoom.getServices()).hasSize(2);
    }

    @Test
    public void testRoomTypeOneToManyRooms() {
        em.getTransaction().begin();

        RoomType suiteType = new RoomType("Suite");
        em.persist(suiteType);

        Room room1 = new Room("301", 2, new BigDecimal("500.00"), suiteType);
        Room room2 = new Room("302", 4, new BigDecimal("750.00"), suiteType);

        suiteType.addRoom(room1);
        suiteType.addRoom(room2);

        em.persist(room1);
        em.persist(room2);

        em.getTransaction().commit();
        em.clear();

        RoomType savedType = em.find(RoomType.class, suiteType.getId());
        assertThat(savedType.getRooms()).hasSize(2);
        assertThat(savedType.getRooms()).extracting(Room::getNumber).containsExactlyInAnyOrder("301", "302");
    }

    @Test
    public void testReservationExtraServiceMapping() {
        em.getTransaction().begin();

        RoomType type = new RoomType("Standard");
        em.persist(type);
        Room room = new Room("404", 2, new BigDecimal("100.00"), type);
        em.persist(room);
        Customer customer = new Customer("Alice", LocalDate.now(), "alice@test.com", "555-1234");
        em.persist(customer);
        Employee employee = new Employee("Bob", "bobadmin", "bob@test.com", EmployeeRole.ADMINISTRATOR);
        employee.setPassword("bobPassword123!");
        em.persist(employee);

        Reservation res = new Reservation();
        res.setCheckInDate(LocalDate.now());
        res.setCheckOutDate(LocalDate.now().plusDays(2));
        res.setNumberOfGuests(1);
        res.setRoom(room);
        res.setEmployee(employee);
        customer.addReservation(res);
        em.persist(res);

        ExtraService massage = new ExtraService("Massage", new BigDecimal("50.00"), "1 hour relaxation");
        em.persist(massage);

        ReservationExtraService resExtra = new ReservationExtraService();
        resExtra.setService(massage);
        resExtra.setQuantity(2);
        resExtra.setPriceAtTime(new BigDecimal("50.00"));

        res.addExtraService(resExtra);
        em.persist(resExtra);

        em.getTransaction().commit();
        em.clear();

        Reservation savedRes = em.find(Reservation.class, res.getId());
        assertThat(savedRes.getExtraServices()).hasSize(1);

        ReservationExtraService fetchedExtra = savedRes.getExtraServices().iterator().next();
        assertThat(fetchedExtra.getQuantity()).isEqualTo(2);
        assertThat(fetchedExtra.getService().getName()).isEqualTo("Massage");
    }

    @Test
    public void testPaymentAndPrePersistLogic() {
        em.getTransaction().begin();

        RoomType type = new RoomType("Penthouse");
        em.persist(type);
        Room room = new Room("505", 2, new BigDecimal("1000.00"), type);
        em.persist(room);
        Customer customer = new Customer("Rich Guy", LocalDate.now(), "rich@test.com", "999-9999");
        em.persist(customer);
        Employee employee = new Employee("Manager", "manager1", "manager@test.com", EmployeeRole.MANAGER);
        employee.setPassword("managerPassword123!");
        em.persist(employee);

        Reservation res = new Reservation();
        res.setCheckInDate(LocalDate.now());
        res.setCheckOutDate(LocalDate.now().plusDays(1));
        res.setNumberOfGuests(2);
        res.setRoom(room);
        res.setEmployee(employee);
        customer.addReservation(res);
        em.persist(res);

        Payment payment = new Payment();
        payment.setAmount(new BigDecimal("1000.00"));
        payment.setMethod(PaymentMethod.CARD);
        payment.setEmployee(employee);

        res.addPayment(payment);
        em.persist(payment);

        em.getTransaction().commit();
        em.clear();

        Payment savedPayment = em.find(Payment.class, payment.getId());
        assertThat(savedPayment).isNotNull();
        assertThat(savedPayment.getAmount()).isEqualByComparingTo(new BigDecimal("1000.00"));

        assertThat(savedPayment.getPaymentDate()).isNotNull();

        Reservation savedRes = em.find(Reservation.class, res.getId());
        assertThat(savedRes.getPayments()).hasSize(1);
    }
}