/**
 * Note: GENERATED BY AI (gemini)
 */

package cz.fit.hotel.repository;

import cz.fit.hotel.model.Customer;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerRepositoryTest {

    private static EntityManagerFactory emf;
    private EntityManager em;
    private CustomerRepository customerRepository;

    @BeforeAll
    public static void init() {
        // Boot up H2 database using the test persistence.xml
        emf = Persistence.createEntityManagerFactory("hotel-test-pu");
    }

    @AfterAll
    public static void tearDown() {
        if (emf != null) emf.close();
    }

    @BeforeEach
    public void setup() throws Exception {
        em = emf.createEntityManager();
        customerRepository = new CustomerRepository();

        // Use Java Reflection to inject the EntityManager into the private @PersistenceContext field
        Field emField = CustomerRepository.class.getDeclaredField("em");
        emField.setAccessible(true);
        emField.set(customerRepository, em);
    }

    @AfterEach
    public void cleanup() {
        if (em != null) em.close();
    }

    @Test
    public void testSaveAndFindById() {
        em.getTransaction().begin();

        Customer customer = new Customer("Test User", LocalDate.of(1985, 10, 15), "test@example.com", "111-222-3333");
        customerRepository.save(customer); // Test the save method

        em.getTransaction().commit();
        em.clear(); // Clear memory cache

        // Test the findById method
        Customer found = customerRepository.findById(customer.getId());

        assertThat(found).isNotNull();
        assertThat(found.getName()).isEqualTo("Test User");
        assertThat(found.getEmail()).isEqualTo("test@example.com");
    }

    @Test
    public void testFindByPhone() {
        em.getTransaction().begin();

        Customer c1 = new Customer("Alice", LocalDate.of(1990, 1, 1), "alice@test.com", "555-0001");
        Customer c2 = new Customer("Bob", LocalDate.of(1992, 2, 2), "bob@test.com", "555-0002");

        customerRepository.save(c1);
        customerRepository.save(c2);

        em.getTransaction().commit();

        // Search for existing phone
        Customer foundAlice = customerRepository.findByPhone("555-0001");
        assertThat(foundAlice).isNotNull();
        assertThat(foundAlice.getName()).isEqualTo("Alice");

        // Search for non-existing phone (should return null safely)
        Customer missing = customerRepository.findByPhone("999-9999");
        assertThat(missing).isNull();
    }

    @Test
    public void testUpdateAndDelete() {
        em.getTransaction().begin();
        Customer c = new Customer("Charlie", LocalDate.now(), "charlie@test.com", "123");
        customerRepository.save(c);
        em.getTransaction().commit();

        // Test Update
        em.getTransaction().begin();
        c.setName("Charlie Updated");
        customerRepository.update(c);
        em.getTransaction().commit();

        assertThat(customerRepository.findById(c.getId()).getName()).isEqualTo("Charlie Updated");

        // Test Delete
        em.getTransaction().begin();
        customerRepository.delete(c);
        em.getTransaction().commit();

        assertThat(customerRepository.findById(c.getId())).isNull();
    }
}