/**
 * Note: GENERATED BY AI (gemini)
 */

package cz.fit.hotel.repository;

import cz.fit.hotel.model.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservationRepositoryTest {

    private static EntityManagerFactory emf;
    private EntityManager em;
    private ReservationRepository reservationRepository;

    @BeforeAll
    public static void init() {
        emf = Persistence.createEntityManagerFactory("hotel-test-pu");
    }

    @AfterAll
    public static void tearDown() {
        if (emf != null) emf.close();
    }

    @BeforeEach
    public void setup() throws Exception {
        em = emf.createEntityManager();
        reservationRepository = new ReservationRepository();

        Field emField = ReservationRepository.class.getDeclaredField("em");
        emField.setAccessible(true);
        emField.set(reservationRepository, em);
    }

    @AfterEach
    public void cleanup() {
        if (em != null) em.close();
    }

    private Reservation createValidReservation(LocalDate checkIn, LocalDate checkOut, ReservationStatus status) {
        RoomType type = new RoomType("Standard-" + System.nanoTime());
        em.persist(type);
        Room room = new Room("101-" + System.nanoTime(), 2, new BigDecimal("100"), type);
        em.persist(room);

        Customer customer = new Customer("Test Customer", LocalDate.of(1990, 1, 1), "test@test.com", "123-" + System.nanoTime());
        em.persist(customer);

        Employee employee = new Employee("Staff", "staff-" + System.nanoTime(), "contact", EmployeeRole.RECEPTIONIST);
        employee.setPassword("pass");
        em.persist(employee);

        Reservation res = new Reservation();
        res.setCheckInDate(checkIn);
        res.setCheckOutDate(checkOut);
        res.setNumberOfGuests(1);
        res.setRoom(room);
        res.setCustomer(customer);
        res.setEmployee(employee);
        res.setStatus(status);
        res.setPaymentStatus(PaymentStatus.UNPAID);

        return res;
    }

    @Test
    public void testSaveAndFindById() {
        em.getTransaction().begin();
        Reservation res = createValidReservation(LocalDate.now(), LocalDate.now().plusDays(3), ReservationStatus.PENDING);
        reservationRepository.save(res);
        em.getTransaction().commit();
        em.clear();

        Reservation found = reservationRepository.findById(res.getId());
        assertThat(found).isNotNull();
        assertThat(found.getStatus()).isEqualTo(ReservationStatus.PENDING);
        assertThat(found.getRoom().getNumber()).isNotNull();
    }

    @Test
    public void testCustomerQueries() {
        em.getTransaction().begin();

        Reservation oldRes = createValidReservation(LocalDate.now().minusDays(10), LocalDate.now().minusDays(5), ReservationStatus.CHECKED_OUT);
        reservationRepository.save(oldRes);

        Customer customer = oldRes.getCustomer();

        Reservation newRes = createValidReservation(LocalDate.now(), LocalDate.now().plusDays(2), ReservationStatus.PENDING);
        newRes.setCustomer(customer);
        reservationRepository.save(newRes);

        em.getTransaction().commit();

        List<Reservation> customerReservations = reservationRepository.findByCustomerId(customer.getId());
        assertThat(customerReservations).hasSize(2);

        LocalDate lastCheckout = reservationRepository.findLastCheckoutByCustomerId(customer.getId());
        assertThat(lastCheckout).isEqualTo(LocalDate.now().plusDays(2));
    }

    @Test
    public void testHasActiveReservation() {
        em.getTransaction().begin();

        Reservation activeRes = createValidReservation(LocalDate.now(), LocalDate.now().plusDays(3), ReservationStatus.PENDING);
        reservationRepository.save(activeRes);
        Customer activeCustomer = activeRes.getCustomer();

        Reservation canceledRes = createValidReservation(LocalDate.now(), LocalDate.now().plusDays(3), ReservationStatus.CANCELED);
        reservationRepository.save(canceledRes);
        Customer canceledCustomer = canceledRes.getCustomer();

        em.getTransaction().commit();

        assertThat(reservationRepository.hasActiveReservation(activeCustomer.getId())).isTrue();

        assertThat(reservationRepository.hasActiveReservation(canceledCustomer.getId())).isFalse();
    }

    @Test
    public void testRoomOverlapLogic() {
        em.getTransaction().begin();

        LocalDate start = LocalDate.of(2026, 5, 10);
        LocalDate end = LocalDate.of(2026, 5, 15);

        Reservation existingRes = createValidReservation(start, end, ReservationStatus.PENDING);
        reservationRepository.save(existingRes);
        Long roomId = existingRes.getRoom().getId();

        em.getTransaction().commit();

        boolean partialLeftOverlap = reservationRepository.hasRoomOverlapExcludingReservation(roomId, start.minusDays(2), start.plusDays(2), -1L);
        assertThat(partialLeftOverlap).isTrue();

        boolean beforeNoOverlap = reservationRepository.hasRoomOverlapExcludingReservation(roomId, start.minusDays(5), start, -1L);
        assertThat(beforeNoOverlap).isFalse();

        em.getTransaction().begin();
        Reservation canceledRes = createValidReservation(start.plusDays(20), start.plusDays(25), ReservationStatus.CANCELED);
        canceledRes.setRoom(existingRes.getRoom());
        reservationRepository.save(canceledRes);
        em.getTransaction().commit();

        boolean canceledOverlap = reservationRepository.hasRoomOverlapExcludingReservation(roomId, start.plusDays(20), start.plusDays(25), -1L);
        assertThat(canceledOverlap).isFalse();
    }

    @Test
    public void testFindBetweenDates() {
        em.getTransaction().begin();

        LocalDate targetStart = LocalDate.of(2026, 12, 24);
        LocalDate targetEnd = LocalDate.of(2026, 12, 26);

        Reservation christmasRes = createValidReservation(targetStart, targetEnd, ReservationStatus.PENDING);
        reservationRepository.save(christmasRes);

        em.getTransaction().commit();

        List<Reservation> found = reservationRepository.findBetweenDates(LocalDate.of(2026, 12, 1), LocalDate.of(2026, 12, 31));
        assertThat(found).hasSize(1);

        List<Reservation> notFound = reservationRepository.findBetweenDates(LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));
        assertThat(notFound).isEmpty();
    }
}