/**
 * Note: GENERATED BY AI (gemini)
 */

package cz.fit.hotel.repository;

import cz.fit.hotel.model.Room;
import cz.fit.hotel.model.RoomType;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomRepositoryTest {

    private static EntityManagerFactory emf;
    private EntityManager em;
    private RoomRepository roomRepository;
    private RoomTypeRepository roomTypeRepository;

    @BeforeAll
    public static void init() {
        emf = Persistence.createEntityManagerFactory("hotel-test-pu");
    }

    @AfterAll
    public static void tearDown() {
        if (emf != null) emf.close();
    }

    @BeforeEach
    public void setup() throws Exception {
        em = emf.createEntityManager();
        roomRepository = new RoomRepository();
        roomTypeRepository = new RoomTypeRepository();

        // Inject EntityManager into RoomRepository
        Field emFieldRoom = RoomRepository.class.getDeclaredField("em");
        emFieldRoom.setAccessible(true);
        emFieldRoom.set(roomRepository, em);

        // Inject EntityManager into RoomTypeRepository
        Field emFieldType = RoomTypeRepository.class.getDeclaredField("em");
        emFieldType.setAccessible(true);
        emFieldType.set(roomTypeRepository, em);
    }

    @AfterEach
    public void cleanup() {
        if (em != null) em.close();
    }

    @Test
    public void testSaveAndFindByNumber() {
        em.getTransaction().begin();

        // Save required RoomType first
        RoomType suiteType = new RoomType("Suite");
        roomTypeRepository.save(suiteType);

        // Save Room
        Room room = new Room("S-101", 4, new BigDecimal("450.00"), suiteType);
        roomRepository.save(room);

        em.getTransaction().commit();
        em.clear();

        // Use custom query to find Room by Number
        Room foundRoom = roomRepository.findByNumber("S-101");

        assertThat(foundRoom).isNotNull();
        assertThat(foundRoom.getCapacity()).isEqualTo(4);
        assertThat(foundRoom.getType().getName()).isEqualTo("Suite");
    }

    @Test
    public void testFindByTypeName() {
        em.getTransaction().begin();

        RoomType basic = new RoomType("Basic");
        RoomType premium = new RoomType("Premium");
        roomTypeRepository.save(basic);
        roomTypeRepository.save(premium);

        roomRepository.save(new Room("101", 2, BigDecimal.TEN, basic));
        roomRepository.save(new Room("102", 2, BigDecimal.TEN, basic));
        roomRepository.save(new Room("201", 4, BigDecimal.TEN, premium));

        em.getTransaction().commit();

        // Check if query properly groups by RoomType Name
        List<Room> basicRooms = roomRepository.findByTypeName("Basic");
        assertThat(basicRooms).hasSize(2);

        List<Room> premiumRooms = roomRepository.findByTypeName("Premium");
        assertThat(premiumRooms).hasSize(1);
        assertThat(premiumRooms.get(0).getNumber()).isEqualTo("201");
    }
}